#!/usr/bin/env ansible-playbook
---
- hosts: local
  become: true
  become_user: dlaliberte
  become_method: sudo
  tasks:
    - name: Install list of apt packages
      apt: name="{{item}}" state=installed
      with_items:
           # utils
           - tmux
           - tree
           # language
           - ruby-full
           # db 
           - sqlite3 
           - postgresql
           - postgresql-contrib
           - pgadmin3
           # misc
           - libpq-dev
           # ansible-lint
           - libffi-dev
           # python-ldap
           - libldap2-dev
           - libsasl2-dev
           - libssl-dev

    - name: Install Python Tools (pip)
      pip: name="{{item}}"
      with_items:
           - virtualenvwrapper
           - ansible-lint

    - name: Add virtualenv workon home to zshrc
      lineinfile: dest=/home/dlaliberte/.zshrc line="export WORKON_ROME=~/Envs"

    - name: Add virtualenvwrapper to zsh
      lineinfile: dest=/home/dlaliberte/.zshrc line="source /usr/local/bin/virtualenvwrapper.sh"

    - name: Install homeshick to manage dotfiles
      git: repo=https://github.com/andsens/homeshick.git dest=/home/dlaliberte/.homesick/repos/homeshick update=no
      #todo get home from variables

    - name: Add Homeshick to bashrc
      lineinfile: dest=/home/dlaliberte/.zshrc line="source /home/dlaliberte/.homesick/repos/homeshick/homeshick.sh"

    - name: Download dotfiles
      git: repo=https://github.com/denislaliberte/dotfiles.git dest=/home/dlaliberte/.homesick/repos/dotfiles update=no


#  roles:
#    - { role: mashimom.oh-my-zsh, ohmyzsh_theme: 'lambda', ohmyzsh_user: 'dlaliberte' }
#    - { role: FGtatsuro.vagrant }
#    - { role: rvm_io.rvm1-ruby, tags: ruby, sudo: True }
#    - { role: ANXS.postgresql  }
#    - { role: hadenlabs.virtualenvwrapper }
#    - cmprescott.chrome
