#!/usr/bin/env ansible-playbook
---
- hosts: local
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: Install list of apt packages
      apt: name="{{item}}" state=installed
      with_items:
           - tmux
           - tree
           - libpq-dev
           # ansible-lint
           - libffi-dev
           # python-ldap
           - libldap2-dev
           - libsasl2-dev
           - libssl-dev
           
    - name: Install list of pip packages
      pip: name="{{item}}"
      with_items:
           - virtualenvwrapper
           - ansible-lint

  roles:
     - { role: mashimom.oh-my-zsh, ohmyzsh_theme: 'lambda', ohmyzsh_user: 'GARDA\\dlaliber' }

#    - { role: rvm_io.rvm1-ruby, tags: ruby, sudo: True }
#    - { role: ANXS.postgresql  }
#    - { role: hadenlabs.virtualenvwrapper }

#  roles:
#    - cmprescott.chrome
